version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: translation
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
